In [1]:
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
import scipy.linalg as slg

In [2]:
def block_diag(A):
    n = A.shape[0]
    m = int(sqrt(n))
    A_reshaped = A.reshape(m, m, m, m)
    A_reshaped = A_reshaped.transpose(0, 2, 1, 3)
    idx = np.arange(m)
    blocks = A_reshaped[idx, idx, :, :]
    return blocks

In [3]:
A = np.random.randn(4, 4)

In [6]:
A

array([[ 0.23745935,  0.24952262, -0.02741168,  0.47137558],
       [-0.00507654, -0.19949644, -1.34998457,  0.06164995],
       [-0.91551757,  1.20508619,  0.23631549, -0.04445129],
       [-1.24482866,  1.73719589, -1.21790224,  0.37500718]])

In [7]:
valid_idx = np.array([True, True, True, False])

In [13]:
A[np.ix_(valid_idx, valid_idx)]

array([[ 0.23745935,  0.24952262, -0.02741168],
       [-0.00507654, -0.19949644, -1.34998457],
       [-0.91551757,  1.20508619,  0.23631549]])

In [11]:
valid_idx[:, None]

array([[ True],
       [ True],
       [ True],
       [False]])